# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09665493941e550151fb526efff73ab732c156e1f1451872fe6786126bc292a59449c87a9d1ce14a6e7b79b3c874c88731122b0bd975c23f4da9db89a4e6c280

test:
  secret_key_base: 257a70ccb7eb736a9518dafc7143f05489b8bba9c48b1f1848e7b345cedabbf73f5a4b71d1bf2b5a18c313abbee2153694dcb1ab1cb6c06e3b20551ace96345a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
